version: "3"

services:
  backend:
    build:
      context: ./back
      dockerfile: DockerFile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./front
      dockerfile: DockerFile
    ports:
      - "3000:3000"