version: "3"

services:
  backend:
    build:
      context: ./back
      dockerfile: DockerFile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"